CREATE DATABASE IF NOT EXISTS library_db;

USE library_db;

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  first_name VARCHAR (255) NOT NULL DEFAULT "",
  last_name VARCHAR (255) NOT NULL DEFAULT "",
  email NVARCHAR (230) NOT NULL DEFAULT "",
  password NVARCHAR (255) NOT NULL DEFAULT ""
);

CREATE TABLE IF NOT EXISTS books (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR (255) NOT NULL,
  description TEXT,
  author VARCHAR (255) NOT NULL,
  publication_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  added_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT reader_id FOREIGN KEY (id) REFERENCES users (id)
);