# fly.toml app configuration file generated for personal-library-app on 2023-06-29T23:02:31+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "personal-library-app"
primary_region = "lax"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
