CREATE DATABASE IF NOT EXISTS library_db;
USE library_db;

CREATE TABLE IF NOT EXISTS users (
  id VARCHAR(255) NOT NULL PRIMARY KEY UNIQUE,
  firstName VARCHAR(255),
  lastName VARCHAR(255),
  fullName VARCHAR(255),
  passwordEnabled BOOLEAN,
  primaryEmailAddress VARCHAR(255),
  emailAddresses JSON,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  externalAccounts JSON,
  verifiedExternalAccounts JSON,
  web3Wallets JSON,
  primaryWeb3Wallet JSON
);

CREATE TABLE IF NOT EXISTS libraries (
  id VARCHAR(36) NOT NULL PRIMARY KEY DEFAULT (UUID()),
  userId VARCHAR(255) UNIQUE,
  books JSON,
  FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE
);